name: 新功能提案
description: 对已有功能的大幅度修改，或添加一个新内容或选项
labels: enhancement, needs-triage
type: Feature
#assignees: PythonSmall-Q, boomzero, shihongxi
title: "[Feature Request]"
body:
- type: checkboxes
  attributes:
    label: 检查项
    description: 请逐个检查下列项目，并勾选确认。
    options:
    - label: 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
      required: true
    - label: 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。
      required: true
- type: textarea
  attributes:
    label: 描述
    description: 详细描述你想添加的功能具体是怎样的。
  validations:
    required: true
- type: textarea
  attributes:
    label: 原因
    description: 详细描述你为什么需要这项功能。
