name: Update Production

on:
  push:
    branches:
      - create-pull-request/patch

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write

jobs:
  update-production:
    name: Merge master into production after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches
      - name: Merge Master to Production branch
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ github.token }}
          from_branch: create-pull-request/patch
          to_branch: dev
