name: Release
on:
  push:
    branches:
      - master
    paths:
      - XMOJ.user.js
jobs:
  Release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: node ./Update/GetVersion.js
      - id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: XMOJ.user.js
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 89969bdf9d5ab8202f8ad8b8ae2c40b8
          projectName: xmoj-script
          directory: .
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - uses: actions/deploy-pages@v4
