name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          filter-threshold: 0.75
          title-excludes: 'bug, not, 1234'
          comment-title: '### We have found some similar issues see'
          comment-body: '${index}. ${similarity} #${number}'
